Acme\PortfolioBundle\Entity\Post:
    type: entity
    table: Post
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        date:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        rating:
            type: float
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        locale:
            type: string
            scale: 0
            length: 2
            unique: false
            nullable: false
            precision: 0
        slug:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        description:
            type: string
            scale: 0
            length: 1024
            unique: false
            nullable: false
            precision: 0
    lifecycleCallbacks: {  }
