acme_security:
    resource: "@AcmeSecurityBundle/Resources/config/routing.yml"
    prefix:   /

acme_admin:
    resource: "@AcmeAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin/

acme_portfolio:
    resource: "@AcmePortfolioBundle/Resources/config/routing.yml"
