security:
    firewalls:
        portfolio:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path: security_login
                check_path: security_login_check
            logout:
                path: security_logout
                target: /%locale%

    access_control:
        -
            path: ^/admin
            allow_if: "has_role('ROLE_ADMIN') or (has_role('ROLE_USER') and '127.0.0.1' == request.getClientIp() and 'localhost.symfony-tutorial.com' == request.getHost() and request.getMethod() in ['GET'])"

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
