security:
    firewalls:
        portfolio:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path: security_login
                check_path: security_login_check
            logout:
                path: security_logout
                target: /%locale%

    access_control:
        - { path: ^/admin, roles: ROLE_USER, host: ^localhost.symfony-tutorial\.com$, ip: 127.0.0.1, methods: [GET] }
        - { path: ^/admin, roles: ROLE_ADMIN, host: ^localhost.symfony-tutorial\.com$ }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
