portfolio_home_index:
    path: /{_locale}
    defaults: { _controller: 'AcmePortfolioBundle:Home:index', _locale: 'en' }
    requirements:
        _locale: en|es

portfolio_home_accept_cookies:
    path: /accept-cookies
    defaults: { _controller: 'AcmePortfolioBundle:Home:acceptCookies' }

portfolio_about_index:
    path: /{_locale}/about.{_format}
    defaults: { _controller: 'AcmePortfolioBundle:About:index', _format: html, _locale: 'en' }
    requirements:
        _locale: en|es

portfolio_blog:
    resource: "@AcmePortfolioBundle/Controller/BlogController.php"
    type: annotation

portfolio_contact_index:
    path: /{_locale}/contact
    defaults: { _controller: 'AcmePortfolioBundle:Contact:index', _locale: 'en' }
    requirements:
        _locale: en|es
