
portfolio_home_index:
    path: /
    defaults: { _controller: 'AcmePortfolioBundle:Home:index' }


portfolio_about_index:
    path: /about
    defaults: { _controller: 'AcmePortfolioBundle:About:index' }


portfolio_blog:
    resource: "@AcmePortfolioBundle/Controller/BlogController.php"
    type: annotation


portfolio_contact_index:
    path: /contact
    defaults: { _controller: 'AcmePortfolioBundle:Contact:index' }